Fiap03.Web.MVC/Fiap03.Web.MVC/Controllers/CarroController.cs
using Fiap03.Web.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Transactions;
using Fiap03.DAL.ConnectionFactories;
using Fiap03.DAL.Repositories.Interfaces;
using Fiap03.DAL.Repositories;
using Fiap03.MOD;

namespace Fiap03.Web.MVC.Controllers
{
    public class CarroController : Controller
    {
        private ICarroRepository _carroRepository = new CarroRepository();
        private IMarcaRepository _marcaRepository = new MarcaRepository();
        private IModeloRepository _modeloRepository = new ModeloRepository();

        #region GET
        [HttpGet]
        public ActionResult BuscarModelos(int marcaId)
        {
            //Busca os modelos pelo id da marca
            var listaMod = _modeloRepository.Listar(marcaId);
            //var listaModel = listaMod.Select(m => new ModeloModel(m)).ToList();
            //retorna o JSON array com a lista de modelos
            return Json(listaMod, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ValidarPlaca(string placa)
        {
            var ok = _carroRepository.ValidarPlaca(placa);
            return Json(new { valido = ok }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            CarregarMarcas();
            return View();
        }

        [HttpGet]
        public ActionResult Pesquisar(int ano)
        {
            //Pesquisa os carros no BD
            var listaMod = _carroRepository.BuscarPorAno(ano);
            //Transforma a lista de MOD em Model
            var listaModel = listaMod.Select(c => new CarroModel(c)).ToList();
            //Retorna para a página Listar com a lista de model
            return PartialView("_Lista", listaModel);
        }

        //Abre a tela de edição com o formulário preenchido
        [HttpGet]
        public ActionResult Editar(int id)
        {
            //Pesquisa no banco de dados pelo ID
            var mod = _carroRepository.Buscar(id);
            //Transforma o MOD em MOdel
            var model = new CarroModel(mod);
            //Carregar as marcas para o select
            CarregarMarcas();
            //Retorna para a página com o model
            return View(model);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            //Buscar no banco de dados a lista de mod
            var listaMod = _carroRepository.Listar();
            //transforma a lista de mod em model
            var listaModel = new List<CarroModel>();
            listaMod.ToList().ForEach(c => listaModel.Add(new CarroModel(c)));
            //retorna para a página com a lista de model
            return View(listaModel);
        }

        #endregion

        #region POST

        [HttpPost]
        public ActionResult Editar(CarroModel model)
        {
            if (!ModelState.IsValid)
            {
                return Editar(model.Id);
            }
            //transforma o model em mod
            CarroMOD mod = ConverterModelParaMOD(model);
            //chama o repository para editar
            _carroRepository.Editar(mod);
            TempData["msg"] = "Atualizado com sucesso!";
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Excluir(int codigo)
        {
            _carroRepository.Excluir(codigo);
            TempData["msg"] = "Carro excluído";
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Cadastrar(CarroModel carro)
        {
            if (!_carroRepository.ValidarPlaca(carro.Placa))
            {
                ModelState.AddModelError("Placa", new Exception("Placa já existente"));
            }
            if (!ModelState.IsValid)
            {
                return Cadastrar();
            }
            var mod = ConverterModelParaMOD(carro);
            _carroRepository.Cadastrar(mod);
            TempData["mensagem"] = "Carro registrado!";
            //Redireciona para uma URL, cria uma segunda request
            //para abrir a página de resposta
            //F5 não cadastra novamente
            return RedirectToAction("Cadastrar");
        }

        #endregion

        private static CarroMOD ConverterModelParaMOD(CarroModel model)
        {
            return new CarroMOD()
            {
                Id = model.Id,
                Ano = model.Ano,
                Combustivel = model.Combustivel,
                Descricao = model.Descricao,
                Esportivo = model.Esportivo,
                MarcaId = model.MarcaId,
                Placa = model.Placa,
                Renavam = model.Renavam,
                Documento = new DocumentoMOD()
                {
                    Categoria = model.Documento.Categoria,
                    Renavam = model.Documento.Renavam,
                    DataFabricacao = model.Documento.DataFabricacao
                }
            };
        }

        private void CarregarMarcas()
        {
            //Listar as marcas do banco de dados
            var lista = _marcaRepository.Listar();
            ViewBag.marcas = new SelectList(lista, "Id", "Nome");
        }

    }
}

Fiap03.Web.MVC/Fiap03.Web.MVC/Controllers/MarcaController.cs
using Fiap03.Web.MVC.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using Fiap03.DAL.Repositories.Interfaces;
using Fiap03.DAL.Repositories;
using Fiap03.MOD;

namespace Fiap03.Web.MVC.Controllers
{
    [Authorize]
    public class MarcaController : Controller
    {
        private IMarcaRepository _marcaRepository = new MarcaRepository();

        [HttpGet]
        public ActionResult Detalhar(int id)
        {
            //pesquisa a marca com os carros no BD
            var mod = _marcaRepository.BuscarComCarros(id);
            //transformar o mod em model
            var model = new MarcaModel(mod);
            return View(model);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(MarcaModel marca)
        {
            //Valida os campos do formulário
            if (!ModelState.IsValid)
            {
                //Erro de validação, retorna para a página
                return View(marca); 
            }
            //Transformar de model para mod
            var mod = new MarcaMOD()
            {
                Cnpj = marca.Cnpj,
                DataCriacao = marca.DataCriacao,
                Nome = marca.Nome
            };

            try
            {
                //Chamar o repository (cadastrar) para gravar no BD
                _marcaRepository.Cadastrar(mod);
                TempData["msg"] = "Marca registrada!";
                return RedirectToAction("Cadastrar");
            }
            catch
            {
                TempData["msg"] = "Erro, por favor tente mais tarde";
                return View();
            }
        }

        [HttpGet]
        public ActionResult Listar()
        {
            //Instanciar uma lista de marcaModel
            var listaModel = new List<MarcaModel>();
            //Buscar as marcaMOD do banco de dados
            var listaMod = _marcaRepository.Listar();
            //Converter o MOD para Model
            listaMod.ToList().ForEach(
                c => listaModel.Add(new MarcaModel(c)));
            //Retornar a View com a lsita de marcaModel
            return View(listaModel);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            //Buscar a marcaMOD do banco de dados pelo ID
            var mod = _marcaRepository.Buscar(id);
            //Transformar o MOD para Model
            var model = new MarcaModel(mod);
            //Retornar a View com o Model
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(MarcaModel marca)
        {
            //Transformar o model para mod
            var mod = new MarcaMOD()
            {
                Cnpj = marca.Cnpj,
                Id = marca.Id,
                Nome = marca.Nome
            };
            //Chamar o método do repository para editar
            _marcaRepository.Editar(mod);
            TempData["msg"] = "Marca atualizada";
            return RedirectToAction("Listar");
        }
    }
}

Fiap03.Web.MVC/Fiap03.Web.MVC/Controllers/UsuarioController.cs
using Fiap03.Web.MVC.App_Start;
using Fiap03.Web.MVC.Models;
using Fiap03.Web.MVC.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Fiap03.Web.MVC.Controllers
{
    public class UsuarioController : Controller
    {
        //gerenciador de usuário
        private readonly UserManager<UsuarioModel> _userManager;

        [HttpGet]
        public ActionResult Logout()
        {
            GetAuthenticationManager().SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Index", "Home");
        }

        //login para o usuário
        [HttpGet]
        public ActionResult Login(string ReturnUrl)
        {
            //capturar a URL que o usuário está tentando acessar
            var model = new UsuarioViewModel
            {
                Url = ReturnUrl
            };
            return View(model); //envia a model com a url para a view
        }

        [HttpPost]
        public async Task<ActionResult> Login(UsuarioViewModel model)
        {
            if (!ModelState.IsValid) //valida os campos do formulário
            {
                return View();
            }

            //Busca o usuário no banco de dados
            var usuario = await _userManager.FindAsync(model.Login, model.Senha);

            //valida se encontrou o usuário
            if (usuario != null)
            {
                var identity = await _userManager.CreateIdentityAsync(usuario, 
                    DefaultAuthenticationTypes.ApplicationCookie);
                GetAuthenticationManager().SignIn(identity);
                return Redirect(GetRedirectUrl(model.Url));
            }

            //não encontrou o usuário
            ModelState.AddModelError("", "Usuário e/ou senha inválido");
            return View();
        }

        //cadastrar um usuário
        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Cadastrar(UsuarioViewModel model)
        {
            if (!ModelState.IsValid) //valida se o model está ok
            {
                return View();
            }

            //criar um objeto para persistir no banco de dados
            var usuario = new UsuarioModel
            {
                UserName = model.Login
            };

            //persisti no banco de dados
            var result = await _userManager.CreateAsync(usuario, model.Senha);

            //verifica se cadastrou com sucesso
            if (result.Succeeded)
            {
                //loga o usuário no sistema
                var identity = await _userManager.CreateIdentityAsync(usuario, DefaultAuthenticationTypes.ApplicationCookie);
                GetAuthenticationManager().SignIn(identity);
                //redireciona para a página inicial
                return RedirectToAction("index", "home");
            }

            //Se der erro ao cadastrar o usuário, adiciona os erros para a view
            foreach (var item in result.Errors)
            {
                ModelState.AddModelError("", item);
            }
            return View();
        }

        //construtor para inicializar o gerenciado de usuário
        public UsuarioController()
        {
            _userManager = IdentityConfig.UserManagerFactory.Invoke();
        }

        //liberar os recursos quando o objeto controller for destruido
        protected override void Dispose(bool disposing)
        {
            if (disposing && _userManager != null)
            {
                _userManager.Dispose();
            }
            base.Dispose(disposing);
        }

        private IAuthenticationManager GetAuthenticationManager()
        {
            var ctx = Request.GetOwinContext();
            return ctx.Authentication;
        }
        private string GetRedirectUrl(string returnUrl)
        {
            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
            {
                return Url.Action("index", "home");
            }
            return returnUrl;
        }
    }
}

Fiap03.Web.MVC/Fiap03.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Marcas
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Marcas", "Listar", "Marca", null, new { @class = "dropdown-item" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Cadastrar", "Cadastrar", "Marca", null, new { @class = "dropdown-item" })
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Carros
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Carros", "Listar", "Carro", null, new { @class = "dropdown-item" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Cadastrar", "Cadastrar", "Carro", null, new { @class = "dropdown-item" })
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            @if (User.Identity.IsAuthenticated)
            {
                <div>
                    @User.Identity.Name
                    @Html.ActionLink("Sair", "Logout", "Usuario", null, new { @class = "btn btn-outline-danger" })
                </div>
            }
            else
            {
                <form class="form-inline my-2 my-lg-0" action="/usuario/login" method="post">
                    <input class="form-control mr-sm-2" name="login" type="text" placeholder="Usuário">
                    <input class="form-control mr-sm-2" name="senha" type="password" placeholder="Senha">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button>
                </form>
            }
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/inputmask/inputmask.js"></script>
    <script src="~/Scripts/inputmask/jquery.inputmask.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <!-- Área para as páginas adicionar scripts -->
    @RenderSection("scripts", false)

</body>
</html>